"""
Static mapping lookup tables for human-readable reasons and actionable recommendations.
Guarantees fast, explainable, zero-hallucination security advice without LLM dependency.
"""

SIGNAL_EXPLANATIONS = {
    "KYC_URGENCY_COMBO": "Combines a false claim of KYC expiry with an urgent threat of account suspension to induce panic.",
    "KYC_CLAIM": "Claims urgent KYC or PAN document update is required, a standard pretext for credential harvesting.",
    "OTP_PIN_REQUEST": "Directly requests sensitive authentication credentials (OTP or UPI PIN). Legitimate banks never ask for these.",
    "URGENCY_LANGUAGE": "Employs psychological pressure and strict deadlines to coerce immediate compliance before you can verify.",
    "AUTHORITY_IMPERSONATION": "Falsely claims to represent law enforcement, regulatory authorities, or official bank fraud teams.",
    "REWARD_LURE": "Promises unexpected lottery prizes, cashbacks, or gifts to entice you into approving a payment request.",
    "PAYMENT_REQUEST_TEXT": "Explicitly requests an advance UPI transfer or handling fee.",
    "FAKE_SUPPORT": "Directs you to unofficial customer helpline numbers operated by attackers.",
    "SUSPICIOUS_LINK_PRESENT": "Includes external web hyperlinks designed to redirect you away from secure banking apps.",
    "TYPOSQUATTED_DOMAIN": "Uses a deceptive domain name crafted to impersonate a trusted bank or payment service.",
    "IP_HOST_URL": "Points to an unverified numeric IP address rather than an authenticated branded domain.",
    "SUSPICIOUS_TLD": "Hosted on a high-risk domain extension commonly leveraged for ephemeral phishing infrastructure.",
    "URL_SHORTENER": "Conceals the true destination web address using a link shortening service.",
    "SENSITIVE_KEYWORD_IN_PATH": "Web path contains sensitive keywords indicative of a fake authentication or credential phishing page.",
    "KNOWN_MALICIOUS_URL": "Destination link is flagged as malicious by cybersecurity threat intelligence feeds.",
    "EXCESSIVE_SUBDOMAINS": "Contains unusually deep subdomains designed to bypass simple URL filter heuristics.",
    "PUNYCODE_DOMAIN": "Utilizes internationalized homoglyph characters to visually spoof a legitimate domain.",
    "HIGH_URL_ENTROPY": "URL contains an unusually high density of random characters and digits.",
    "CLAIM_INTENT_MISMATCH": "CRITICAL MISMATCH: You were promised a refund or incoming payment, but this QR code will DEBIT and SEND money from your bank account.",
    "QR_INITIATES_PAYMENT": "Scanning this QR code initiates an outgoing payment (You send money). Remember: you NEVER need to scan a QR or enter your PIN to receive money.",
    "UNVERIFIED_RECIPIENT": "Recipient UPI handle is an unverified individual or non-official merchant VPA.",
    "AMOUNT_PRESENT_UNCONFIRMED": "QR code has a pre-set amount already populated to be charged immediately upon PIN entry.",
    "NON_UPI_QR": "QR code does not follow standard UPI protocol; payload may lead to untrusted external sites.",
    "AMOUNT_ANOMALY": "Transaction amount is more than 5 times greater than your usual spending baseline.",
    "NEW_RECIPIENT": "First-time transfer to a previously unseen recipient handle.",
    "UNUSUAL_TIME": "Transaction initiated during high-risk overnight hours (00:00 - 05:00 AM).",
    "DEVICE_CHANGE": "Payment initiated from a previously unregistered hardware device.",
    "LOCATION_CHANGE": "Transaction originated from a geographic location outside your frequent activity cluster.",
    "ML_TEXT_SCAM_PROBABILITY": "Statistical language patterns strongly resemble documented UPI fraud tactics.",
    "LOW_OCR_CONFIDENCE": "Screenshot text was partially unreadable; please visually confirm details.",
}

SIGNAL_ACTIONS = {
    "KYC_URGENCY_COMBO": "Do not click any link or send documents. Contact your bank branch directly or use the official mobile banking app.",
    "KYC_CLAIM": "Never update KYC via SMS or WhatsApp links. Complete KYC solely within your official banking app.",
    "OTP_PIN_REQUEST": "NEVER enter or share your UPI PIN or OTP. Remember: UPI PIN is ONLY needed to SEND money, never to receive money.",
    "URGENCY_LANGUAGE": "Pause and do not act immediately. Legitimate banks will never demand instant compliance under threat of blocking.",
    "AUTHORITY_IMPERSONATION": "Verify caller identity independently. Government agencies and banks will never demand payment via personal UPI.",
    "REWARD_LURE": "Ignore the prize message. Remember that real refunds are credited automatically without requiring QR scans or PIN entry.",
    "PAYMENT_REQUEST_TEXT": "Decline the payment request immediately.",
    "FAKE_SUPPORT": "Only contact customer care numbers published on the official verified website of your bank.",
    "SUSPICIOUS_LINK_PRESENT": "Do not click or open the link under any circumstance.",
    "TYPOSQUATTED_DOMAIN": "Do not visit the domain. Type the official bank address directly into your browser.",
    "IP_HOST_URL": "Close the page immediately. Legitimate financial institutions never host portals on raw IP addresses.",
    "SUSPICIOUS_TLD": "Avoid navigating to this link.",
    "URL_SHORTENER": "Do not expand or open shortened links from unknown senders.",
    "SENSITIVE_KEYWORD_IN_PATH": "Never enter your banking login ID, password, or card numbers on this page.",
    "KNOWN_MALICIOUS_URL": "Block the sender and report the URL immediately.",
    "EXCESSIVE_SUBDOMAINS": "Do not trust this URL; verify through official search.",
    "PUNYCODE_DOMAIN": "Exit the page immediately.",
    "HIGH_URL_ENTROPY": "Avoid interacting with this suspicious link.",
    "CLAIM_INTENT_MISMATCH": "DO NOT SCAN OR PAY. This is a payment trap. Close your camera and do NOT enter your UPI PIN.",
    "QR_INITIATES_PAYMENT": "Only proceed if you genuinely intended to make a purchase or transfer. You do NOT need to pay to receive money.",
    "UNVERIFIED_RECIPIENT": "Confirm recipient identity through a trusted phone call before authorizing the payment.",
    "AMOUNT_PRESENT_UNCONFIRMED": "Review the exact debited amount carefully before authorizing.",
    "NON_UPI_QR": "Do not open non-UPI payloads unless verified.",
    "AMOUNT_ANOMALY": "Double check the recipient and amount before completing high-value transfers.",
    "NEW_RECIPIENT": "Send a nominal test amount (e.g. ₹1) first if paying this recipient for the first time.",
    "UNUSUAL_TIME": "Verify that this transaction was genuinely initiated by you.",
    "DEVICE_CHANGE": "Check if your account was accessed from an unknown phone or emulator.",
    "LOCATION_CHANGE": "Ensure you are using a secure, private network.",
    "ML_TEXT_SCAM_PROBABILITY": "Exercise extreme caution and verify with official support.",
    "LOW_OCR_CONFIDENCE": "Paste the text directly into IRIS for a more thorough analysis.",
}
